ProxyPreserveHost On

ProxyPass        /wp-json/ http://wordpress/wp-json/
ProxyPassReverse /wp-json/ http://wordpress/wp-json/

ProxyPass        /wp-admin/ http://wordpress/wp-admin/
ProxyPassReverse /wp-admin/ http://wordpress/wp-admin/

ProxyPass        /wp-login.php http://wordpress/wp-login.php
ProxyPassReverse /wp-login.php http://wordpress/wp-login.php

ProxyPass        /wp-content/ http://wordpress/wp-content/
ProxyPassReverse /wp-content/ http://wordpress/wp-content/

ProxyPass        /wp-includes/ http://wordpress/wp-includes/
ProxyPassReverse /wp-includes/ http://wordpress/wp-includes/

ProxyPass        /wp-cron.php http://wordpress/wp-cron.php
ProxyPassReverse /wp-cron.php http://wordpress/wp-cron.php